//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopWebBKB.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            ImagePro = "~/Image/Pet/Dogs/corgi.png";
        }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        public int ID { get; set; }
        public string IDPro { get; set; }
        public string IDFur { get; set; }
        public string IDSize { get; set; }
        public string IDOrigin { get; set; }
        public string IDPopular { get; set; }
        public string NamePro { get; set; }
        public string ImagePro { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<short> Age { get; set; }
        public Nullable<int> SoldQuantity { get; set; }
        public Nullable<int> RemainQuantity { get; set; }
        public string DescriptionPro { get; set; }
        [NotMapped]
        public string ErrorProduct { get; set; }
        public virtual Fur Fur { get; set; }
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Origin Origin { get; set; }
        public virtual Popular Popular { get; set; }
        public virtual Size Size { get; set; }
    }
}
